# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

# build version format
version: "{build}"

# fix lineendings in Windows
init:
  - git config --global core.autocrlf input

# what combinations to test
environment:
  matrix:
    - nodejs_version: 0.10
    - nodejs_version: 0.12
    - nodejs_version: 4
    - nodejs_version: 6

# get the latest stable version of Node 0.STABLE.latest
install:
  # Download Node.js 0.10.48 MSI and install it
  - ps: |
      if ($env:nodejs_version -eq "0.10") {
        # Define the URL for the Node.js version and the MSI installer
        $url = "https://nodejs.org/dist/v0.10.48/node-v0.10.48-x86.msi"
        $installer = "$env:TEMP\node-v0.10.48-x86.msi"
        
        # Download the MSI installer
        Invoke-WebRequest -Uri $url -OutFile $installer

        # Run the MSI installer silently (no UI, no restart)
        Start-Process msiexec.exe -ArgumentList "/i", $installer, "/quiet", "/norestart" -NoNewWindow -Wait

        # Clean up the installer file after installation
        Remove-Item -Path $installer

        # Manually check if Node.js has been installed correctly
        if (-Not (Test-Path "C:\Program Files\nodejs\node.exe")) {
          Write-Error "Node.js installation failed. node.exe not found in C:\Program Files\nodejs"
          exit 1
        }

        # Add Node.js to the PATH environment variable explicitly
        $env:Path += ";C:\Program Files\nodejs"

        # Verify Node.js is now available in the PATH
        if ((Get-Command node -ErrorAction SilentlyContinue) -eq $null) {
          Write-Error "Node.js is still not found in PATH"
          exit 1
        }
      }
  - ps: if ((Get-Command node -ErrorAction SilentlyContinue) -eq $null) {
      Write-Error "Node.js version $env:nodejs_version not found"
      exit 1
    }
  - ps: if ((Get-Command node -ErrorAction SilentlyContinue) -ne $null) { Install-Product node $env:nodejs_version }
  - ps: |
      if ($env:npm_version)
      {
        npm install -g npm@$env:npm_version --loglevel=error
      }
  - npm install --loglevel=error

build: off

test_script:
  - node --version
  - npm --version
  - cmd: npm test --no-color
