# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

# build version format
version: "{build}"

# fix lineendings in Windows
init:
  - git config --global core.autocrlf input

# what combinations to test
environment:
  matrix:
    - nodejs_version: 0.10
    - nodejs_version: 0.12
    - nodejs_version: 4
    - nodejs_version: 6

# get the latest stable version of Node 0.STABLE.latest
install:
  # - ps: Install-Product node $env:nodejs_version
  - ps: if($env:npm_version -eq "^3.0.0"){Update-NodeJsInstallation $env:nodejs_version x86}
  - ps: if($env:npm_version -eq $null){Install-Product node $env:nodejs_version}
  - ps: if ((Get-Command node -ErrorAction SilentlyContinue) -eq $null) { Write-Error "Node.js version $env:nodejs_version not found"; exit 1 }
  - ps: |
       if ($env:npm_version)
       {
        npm install -g npm@$env:npm_version --loglevel=error
       }

  - npm install --loglevel=error

build: off

test_script:
  - node --version
  - npm --version
  - cmd: npm test --no-color
