# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

# build version format
version: "{build}"

# fix lineendings in Windows
init:
  - git config --global core.autocrlf input

# what combinations to test
environment:
  matrix:
    - nodejs_version: 0.10
    - nodejs_version: 0.12
    - nodejs_version: 4
    - nodejs_version: 6

# get the latest stable version of Node 0.STABLE.latest
install:
  # Download Node.js 0.10.48 tar.gz and extract
  - ps: |
      if ($env:nodejs_version -eq "0.10") {
        # Define URL for the Node.js version and target folder
        $url = "https://nodejs.org/dist/v0.10.48/node-v0.10.48-x86.tar.gz"
        $tarball = "$env:TEMP\node-v0.10.48-x86.tar.gz"
        $installDir = "C:\Program Files\nodejs"

        # Download the tarball
        Invoke-WebRequest -Uri $url -OutFile $tarball

        # Use 7-Zip (if installed) to extract the tarball
        # You can also use built-in tar if available in PowerShell or Git Bash
        if (Test-Path "C:\Program Files\7-Zip\7z.exe") {
          & "C:\Program Files\7-Zip\7z.exe" x $tarball -o$installDir -y
        } else {
          tar -xvf $tarball -C $installDir
        }
        
        # Clean up the tarball file
        Remove-Item -Path $tarball
      }
  - ps: if ((Get-Command node -ErrorAction SilentlyContinue) -eq $null) { Write-Error "Node.js version $env:nodejs_version not found"; exit 1 }
  - ps: if ((Get-Command node -ErrorAction SilentlyContinue) -ne $null) { Install-Product node $env:nodejs_version }
  - ps: |
      if ($env:npm_version)
      {
        npm install -g npm@$env:npm_version --loglevel=error
      }
  - npm install --loglevel=error

build: off

test_script:
  - node --version
  - npm --version
  - cmd: npm test --no-color
